# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e471b254a26c96ea7981e96ac06ffac72beb3ab438ed0aefabf6e828b2bda36fa30b9453294c88d95f962927ef20d5996c33a49185097bdbb00ce4f80866578

test:
  secret_key_base: 849c4efabfd44ae0df07e13c52938ef0ab877ad71b58983af750343a37cc1707f2e67b341d10b5e7d7dc41f6a076dca5aafae21782c34012895628c265539287

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
